### ISSUE TITLE
Implementazione token jwt

### ISSUE THREAD

**Issue by rjrb2b** [rjrb2b/rjr.library.2024#3]
Implementazione di uno strato di sicurezza per proteggere le API attraverso un token JWT (JSON Web Token).
Il token JWT sarà incluso nell'header di ogni richiesta API e verrà utilizzato per autenticare e autorizzare gli utenti.

## Task
- [ ] Integrazione della libreria JWT nell'applicazione Spring Boot.
- [ ] Configurazione dei filtri per l'autenticazione e l'autorizzazione.
- [ ] Implementazione della generazione e validazione dei token JWT.
- [ ] Creazione di un endpoint per l'autenticazione e il rilascio dei token JWT.

## Criteri di accettazione
1. Le chiamate API devono essere protette utilizzando token JWT.
2. Gli utenti devono essere autenticati e autorizzati correttamente prima di poter accedere alle risorse protette.
3. I token JWT devono essere generati correttamente e validati in base alle chiavi segrete.
4. Il codice deve essere adeguatamente testato e documentato.
5. L'applicazione deve essere in grado di gestire correttamente le situazioni di autenticazione fallita o token non validi.
